/* Generated By:JavaCC: Do not edit this line. grammarTreeConstants.java Version 5.0 */
package language;

public interface grammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEMPTY = 1;
  public int JJTBLOCDEC = 2;
  public int JJTSUITEBLOCDEC = 3;
  public int JJTBLOCPRINCIPAL = 4;
  public int JJTBLOCSOUSPROGRAMME = 5;
  public int JJTVALEUR = 6;
  public int JJTBLOCINSTRUCTION = 7;
  public int JJTINSTRUCTION = 8;
  public int JJTAPPELPROCEDURE = 9;
  public int JJTARG = 10;
  public int JJTSUITEARG = 11;
  public int JJTAFFECTATION = 12;
  public int JJTBOUCLE = 13;
  public int JJTCONDITION = 14;
  public int JJTSUITECONDITION = 15;
  public int JJTEXPAR = 16;
  public int JJTMULT = 17;
  public int JJTUNARY = 18;
  public int JJTPREUNARY = 19;
  public int JJTELEMENT = 20;
  public int JJTAPPELFUNCTION = 21;
  public int JJTENTIER = 22;
  public int JJTREEL = 23;
  public int JJTSUITEREEL = 24;
  public int JJTEXPLOG = 25;
  public int JJTUNARYL = 26;
  public int JJTELEMENTL = 27;
  public int JJTBOOLEEN = 28;
  public int JJTTEST = 29;
  public int JJTEXPSTRING = 30;
  public int JJTSTRING = 31;
  public int JJTFUNCTION = 32;
  public int JJTTYPE = 33;
  public int JJTID = 34;
  public int JJTPARAM = 35;
  public int JJTSUITEPARAM = 36;
  public int JJTBODY = 37;
  public int JJTPROCEDURE = 38;


  public String[] jjtNodeName = {
    "Start",
    "Empty",
    "BlocDec",
    "SuiteBlocDec",
    "BlocPrincipal",
    "BlocSousProgramme",
    "Valeur",
    "BlocInstruction",
    "Instruction",
    "AppelProcedure",
    "Arg",
    "SuiteArg",
    "Affectation",
    "Boucle",
    "Condition",
    "SuiteCondition",
    "ExpAr",
    "Mult",
    "Unary",
    "PreUnary",
    "Element",
    "AppelFunction",
    "Entier",
    "Reel",
    "SuiteReel",
    "ExpLog",
    "UnaryL",
    "ElementL",
    "booleen",
    "Test",
    "ExpString",
    "string",
    "Function",
    "type",
    "id",
    "Param",
    "SuiteParam",
    "Body",
    "Procedure",
  };
}
/* JavaCC - OriginalChecksum=5188bb1b99c01171dce516f5ca2eaece (do not edit this line) */
